### ISSUE TITLE
Is there a paper about it? and how to generate the 'test data'?

### ISSUE THREAD

**Issue by yl255** [wangqiuwen1006/Medical-3D-Voxel-Classification#2]
Hi,
Thank you for your great work.
Is there a paper about this work?
and in the test.py, how to convert the 'mhd' file to the '.npz' file?
Best,
Yaliang

**Comment by wangqiuwen1006** [comment]
This is just the homework code for the EE228 course,SJTU, So no related papers have been written. And the original files provided in the course are '.npz' files, so I don't know how to use '.mhd' files. Thank you for your attention and hope you can solve the problem.

**Comment by yl255** [comment]
thanks for your work!
